version: '3.8'

services:
  main:
    restart: on-failure
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      PORT: 3000
      UPDATE_INTERVAL: 10
      SERVICE_COMMISSION: 0.01
